# Generated by Django 5.0.1 on 2024-02-03 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_slug_alter_product_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='color',
            new_name='colors',
        ),
    ]
