# Generated by Django 5.0.1 on 2024-02-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new_price',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(related_name='products', to='product.color'),
        ),
    ]
