# Generated by Django 5.0.1 on 2024-02-07 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_new_price_alter_product_colors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='new_price',
        ),
    ]
