# Generated by Django 4.2.5 on 2024-02-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_product_new_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='categoty',
            field=models.ManyToManyField(null=True, related_name='products', to='product.category'),
        ),
    ]
