# Generated by Django 4.2.5 on 2024-02-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_category_product_categoty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categoty',
            field=models.ManyToManyField(related_name='products', to='product.category'),
        ),
    ]
