# Generated by Django 4.2.5 on 2024-02-29 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='messages',
            new_name='message',
        ),
    ]
