# Generated by Django 4.2.5 on 2024-03-05 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_product_created_product_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created', '-updated']},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='categoty',
            new_name='category',
        ),
    ]
