# Generated by Django 4.2.5 on 2024-03-10 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_commentproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentproduct',
            old_name='user',
            new_name='author',
        ),
    ]
