# Generated by Django 5.0.1 on 2024-03-19 16:39

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_product_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['created', 'updated']},
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, null=True),
        ),
    ]
