# Generated by Django 5.0.1 on 2024-03-19 20:48

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_alter_product_options_alter_product_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentproduct',
            name='created',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='commentproduct',
            name='updated',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, null=True),
        ),
    ]
