# Generated by Django 5.1.2 on 2024-12-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_alter_category_options_alter_color_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentproduct',
            name='body',
            field=models.TextField(verbose_name='متن پیام'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products', verbose_name='عکس محصول'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.ImageField(upload_to='team', verbose_name='عکس اعضا'),
        ),
    ]
