# Generated by Django 5.1.2 on 2024-12-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_alter_commentproduct_body_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentproduct',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='commentproduct',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
