# Generated by Django 4.2.5 on 2024-02-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='province',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=40),
        ),
    ]
