# Generated by Django 4.2.5 on 2024-02-10 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_address_taker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='taker',
            new_name='receiver',
        ),
    ]
