# Generated by Django 4.2.5 on 2024-02-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_taker_address_receiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='fullName',
        ),
        migrations.AlterField(
            model_name='address',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
