# Generated by Django 4.2.5 on 2024-02-10 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_orderitem_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
    ]
