# Generated by Django 5.0.1 on 2024-03-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order',
            field=models.TextField(blank=True, null=True),
        ),
    ]
