# Generated by Django 5.0.1 on 2024-03-17 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_order_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order',
            new_name='address',
        ),
    ]
